version: "3.7"
services:
  dev-kit:
    container_name: $DEV_KIT_NAME
    image: "node:$NODE_VERSION"
    working_dir: /app
    volumes:
      - '~/.npmrc:/root/.npmrc'
    env_file:
      - .env
    environment:
      NPM_TOKEN:
    networks:
      - net
    labels:
      eu.rene-simon.dev-kit.types: "tool"
  proxy:
    container_name: "$PROXY_NAME"
    image: "caddy:$PROXY_VERSION"
    env_file:
      - .env
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - ./cert:/config
    networks:
      - net
    labels:
      eu.rene-simon.dev-kit.types: "tool"
    healthcheck:
      test: "wget -qO - https://$HOST:443//health-check --no-check-certificate"
      interval: 15s
      timeout: 2s
      retries: 4
      start_period: 30s

networks:
  net:
    name: "$NETWORK_NAME"
    driver: bridge
