name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  install:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache node modules
        id: cache
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ./node_modules
            ~/.npm
            ~/.npmrc
          key: ${{ runner.os }}-modules-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Set .npmrc
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
      - name: Install node modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
  unit-test:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache node modules
        id: cache
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ./node_modules
            ~/.npm
            ~/.npmrc
          key: ${{ runner.os }}-modules-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Run unit tests
        run: npm run test:ci

  code-duplication:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache node modules
        id: cache
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ./node_modules
            ~/.npm
            ~/.npmrc
          key: ${{ runner.os }}-modules-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Detect duplicate code
        run: npm run jscpd:ci
  build:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache node modules
        id: cache
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ./node_modules
            ~/.npm
            ~/.npmrc
          key: ${{ runner.os }}-modules-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Build
        run: npm run build
      - name: Cache build result
        if: startsWith( github.ref, 'refs/tags/')
        id: build-cache
        uses: actions/cache@v4
        env:
          cache-name: cache-working-directory
        with:
          path: |
            ./.*
            ./*
            ~/.npmrc
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}
  publish:
    if: startsWith( github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Load cached build result
        id: build-cache
        uses: actions/cache@v4
        env:
          cache-name: cache-working-directory
        with:
          path: |
            ./.*
            ./*
            ~/.npmrc
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}
      - name: Publish to npm
        run: |
          npm publish --access public
